-- ============================================================
-- SIGEVIR - SUPABASE SETUP COMPLETO
-- Sistema Integral de Gesti├│n de Veh├¡culos Retenidos
-- ============================================================
-- Ejecutar este SQL en el SQL Editor de Supabase
-- ============================================================

-- ##############################
-- 1. TABLA: tipos_personal
-- ##############################
CREATE TABLE IF NOT EXISTS tipos_personal (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  nombre VARCHAR(100) NOT NULL UNIQUE,
  rol_asignado VARCHAR(50) NOT NULL,
  descripcion TEXT,
  activo BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE tipos_personal IS 'Cat├ílogo de tipos de personal y su mapeo a roles del sistema';
COMMENT ON COLUMN tipos_personal.nombre IS 'Nombre del tipo de personal (Polic├¡a, Juez, etc.)';
COMMENT ON COLUMN tipos_personal.rol_asignado IS 'Rol que se asigna autom├íticamente (agente_campo, deposito, fiscal_juez, admin)';

-- Seed data: tipos de personal
INSERT INTO tipos_personal (nombre, rol_asignado, descripcion) VALUES
  ('Polic├¡a', 'agente_campo', 'Oficial de polic├¡a que realiza retenciones en v├¡a p├║blica'),
  ('Inspector de tr├ínsito', 'agente_campo', 'Inspector municipal que realiza retenciones en v├¡a p├║blica'),
  ('Responsable de dep├│sito', 'deposito', 'Encargado del corral├│n o dep├│sito municipal'),
  ('Juez', 'fiscal_juez', 'Juez interviniente en causas judiciales'),
  ('Fiscal', 'fiscal_juez', 'Fiscal interviniente en causas judiciales'),
  ('Secretario judicial', 'fiscal_juez', 'Secretario auxiliar de juzgado o fiscal├¡a'),
  ('Administrador', 'admin', 'Administrador del sistema con acceso completo')
ON CONFLICT (nombre) DO NOTHING;

-- ##############################
-- 2. TABLA: perfiles
-- ##############################
CREATE TABLE IF NOT EXISTS perfiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  nombre_completo VARCHAR(255) NOT NULL,
  dni VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL,
  telefono VARCHAR(50),
  institucion VARCHAR(255) NOT NULL,
  jurisdiccion VARCHAR(255),
  cargo VARCHAR(255),
  tipo_personal_id BIGINT REFERENCES tipos_personal(id),
  rol VARCHAR(50) NOT NULL DEFAULT 'agente_campo',
  activo BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

COMMENT ON TABLE perfiles IS 'Perfiles de usuario del sistema SIGEVIR, vinculados a auth.users';
COMMENT ON COLUMN perfiles.id IS 'Misma UUID que auth.users.id';
COMMENT ON COLUMN perfiles.rol IS 'Rol asignado autom├íticamente seg├║n tipo_personal';

-- ##############################
-- 3. FUNCI├ôN TRIGGER: handle_new_user
-- ##############################
CREATE OR REPLACE FUNCTION handle_new_user()
RETURNS TRIGGER
SECURITY DEFINER SET search_path = public
LANGUAGE plpgsql
AS 
DECLARE
  v_tipo_personal_id BIGINT;
  v_rol VARCHAR(50);
  v_nombre_completo TEXT;
  v_dni TEXT;
  v_telefono TEXT;
  v_cargo TEXT;
  v_institucion TEXT;
  v_jurisdiccion TEXT;
BEGIN
  -- Extraer metadata del registro en auth.users
  v_nombre_completo := NEW.raw_user_meta_data ->> 'nombre_completo';
  v_dni := NEW.raw_user_meta_data ->> 'dni';
  v_telefono := NEW.raw_user_meta_data ->> 'telefono';
  v_cargo := NEW.raw_user_meta_data ->> 'cargo';
  v_institucion := NEW.raw_user_meta_data ->> 'institucion';
  v_jurisdiccion := NEW.raw_user_meta_data ->> 'jurisdiccion';
  v_tipo_personal_id := (NEW.raw_user_meta_data ->> 'tipo_personal_id')::BIGINT;

  -- Obtener el rol asignado seg├║n el tipo de personal
  SELECT rol_asignado INTO v_rol
  FROM tipos_personal
  WHERE id = v_tipo_personal_id;

  -- Si no se encontr├│ rol, asignar agente_campo por defecto
  IF v_rol IS NULL THEN
    v_rol := 'agente_campo';
  END IF;

  -- Crear perfil
  INSERT INTO public.perfiles (
    id, nombre_completo, dni, email, telefono,
    institucion, jurisdiccion, cargo,
    tipo_personal_id, rol, activo
  ) VALUES (
    NEW.id,
    COALESCE(v_nombre_completo, 'Sin nombre'),
    COALESCE(v_dni, '00000000'),
    NEW.email,
    v_telefono,
    COALESCE(v_institucion, 'Sin instituci├│n'),
    v_jurisdiccion,
    v_cargo,
    v_tipo_personal_id,
    COALESCE(v_rol, 'agente_campo'),
    true
  );

  RETURN NEW;
END;
;

-- Trigger: ejecutar handle_new_user despu├®s de crear un usuario en auth.users
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW
  EXECUTE FUNCTION handle_new_user();

-- ##############################
-- 4. FUNCI├ôN: actualizar updated_at
-- ##############################
CREATE OR REPLACE FUNCTION update_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
AS 
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
;

CREATE TRIGGER perfiles_updated_at
  BEFORE UPDATE ON perfiles
  FOR EACH ROW
  EXECUTE FUNCTION update_updated_at();

-- ##############################
-- 5. ├ìNDICES
-- ##############################
CREATE INDEX IF NOT EXISTS idx_perfiles_rol ON perfiles(rol);
CREATE INDEX IF NOT EXISTS idx_perfiles_institucion ON perfiles(institucion);
CREATE INDEX IF NOT EXISTS idx_perfiles_dni ON perfiles(dni);
CREATE INDEX IF NOT EXISTS idx_perfiles_email ON perfiles(email);
CREATE INDEX IF NOT EXISTS idx_perfiles_tipo_personal ON perfiles(tipo_personal_id);
CREATE INDEX IF NOT EXISTS idx_perfiles_activo ON perfiles(activo);
CREATE INDEX IF NOT EXISTS idx_tipos_personal_rol ON tipos_personal(rol_asignado);

-- ##############################
-- 6. ROW LEVEL SECURITY (RLS)
-- ##############################

-- Habilitar RLS en perfiles
ALTER TABLE perfiles ENABLE ROW LEVEL SECURITY;

-- Pol├¡tica 1: Admin puede ver y gestionar todo
CREATE POLICY admin_perfiles_all ON perfiles
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM perfiles
      WHERE id = auth.uid() AND rol = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM perfiles
      WHERE id = auth.uid() AND rol = 'admin'
    )
  );

-- Pol├¡tica 2: Usuario puede ver su propio perfil
CREATE POLICY usuario_perfiles_self ON perfiles
  FOR SELECT
  TO authenticated
  USING (id = auth.uid());

-- Pol├¡tica 3: fiscal_juez puede ver todos los perfiles
CREATE POLICY fiscal_juez_perfiles_select ON perfiles
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM perfiles
      WHERE id = auth.uid() AND rol = 'fiscal_juez'
    )
  );

-- Pol├¡tica 4: agente_campo y deposito ven perfiles de su misma instituci├│n
CREATE POLICY agente_deposito_perfiles_select ON perfiles
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM perfiles p
      WHERE p.id = auth.uid()
      AND p.rol IN ('agente_campo', 'deposito')
      AND p.institucion = perfiles.institucion
    )
  );

-- Habilitar RLS en tipos_personal
ALTER TABLE tipos_personal ENABLE ROW LEVEL SECURITY;

-- Todos los usuarios autenticados pueden leer tipos_personal
CREATE POLICY tipos_personal_select ON tipos_personal
  FOR SELECT
  TO authenticated
  USING (true);

-- Solo admin puede modificar tipos_personal
CREATE POLICY tipos_personal_admin ON tipos_personal
  FOR ALL
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM perfiles
      WHERE id = auth.uid() AND rol = 'admin'
    )
  )
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM perfiles
      WHERE id = auth.uid() AND rol = 'admin'
    )
  );

-- ##############################
-- 7. CONFIGURACI├ôN AUDITOR├ìA
-- ##############################

-- Tabla para auditor├¡a de cambios en perfiles
CREATE TABLE IF NOT EXISTS auditoria_perfiles (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  perfil_id UUID REFERENCES perfiles(id) ON DELETE SET NULL,
  usuario_accion UUID REFERENCES auth.users(id),
  accion VARCHAR(50) NOT NULL,
  datos_anteriores JSONB,
  datos_nuevos JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE auditoria_perfiles ENABLE ROW LEVEL SECURITY;

-- Solo admin puede ver auditor├¡a
CREATE POLICY auditoria_admin_select ON auditoria_perfiles
  FOR SELECT
  TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM perfiles
      WHERE id = auth.uid() AND rol = 'admin'
    )
  );

CREATE INDEX IF NOT EXISTS idx_auditoria_perfil ON auditoria_perfiles(perfil_id);
CREATE INDEX IF NOT EXISTS idx_auditoria_fecha ON auditoria_perfiles(created_at);
